import json

# List of doctor names
doctor_names = [
    "Dietitian Ekta",
    "Dr. Aabid Amin Bhatt",
    "Dr. Aseem Trikha",
    "Dr. Bhoopender Singh",
    "Dr. Jalaz Jain",
    "Dr. M. Ayub Thoker",
    "Dr. Mir Mehfooza Gani",
    "Dr. Nadeem Ahmad",
    "Dr. Nikita Sachdeva",
    "Dr. Parvesh Malik",
    "Dr. Priyadarshini",
    "Dr. Priyanka Gupta",
    "Dr. Sajad Sultan Loan",
    "Dr. Sandeep Khasa",
    "Dr. Vardhan Kulshrestha",
    "Dr. (Major) Ravinder Singh",
    "Dr. (Major) Saurabh Mayank",
    "Dr. A Hussain",
    "Dr. Aadil Beigh",
    "Dr. Aarif Hussain Bhat",
    "Dr. Abdul Sameer Qureshi",
    "Dr. Abhijeet Bhandari",
    "Dr. Abhijeet Ranjan",
    "Dr. Abhijit Patel",
    "Dr. Abhishek Mittal",
    "Dr. Abhishek Sakwariya",
    "Dr. Adfer Gul",
    "Dr. Aditya Chaudhari",
    "Dr. Aftab Ahmad",
    "Dr. Ainam",
    "Dr. Ajay Dubey",
    "Dr. Ajay Kumar T Prasad",
    "Dr. Akanksha Arora",
    "Dr. Akansha Arora Gupta",
    "Dr. Akta Bajaj",
    "Dr. Amanat Kaur",
    "Dr. Amit Gupta",
    "Dr. Amit Ranjan",
    "Dr. Amit Singhal",
    "Dr. Amit Yadav",
    "Dr. Anamika Yadav",
    "Dr. Anand Ayanger",
    "Dr. Anil M Pal",
    "Dr. Ankur Kumar",
    "Dr. Anoop Khare",
    "Dr. Anshul Kedia",
    "Dr. Anshul Mangla",
    "Dr. Anu yadav",
    "Dr. Anubhav Arya",
    "Dr. Anupama Yadav",
    "Dr. Ashok Kumar",
    "Dr. Azim Ilyas",
    "Dr. B.N Mishra",
    "Dr. Beenu Tripathi",
    "Dr. Bharat Yadav",
    "Dr. Bhavya Gupta",
    "Dr. Bhawani Shankar",
    "Dr. Bhupendra Verma",
    "Dr. Bilal Akbar",
    "Dr. Chakresh Kumar Jain",
    "Dr. Danish Andrabi",
    "Dr. Deepak Agrahari",
    "Dr. Deepak Bhardwaj",
    "Dr. Deepak Kumar",
    "Dr. Deepak Kumar Singh",
    "Dr. Deepak Rai",
    "Dr. Deepak Sharma",
    "Dr. Deepika Kamra",
    "Dr. Deepti Bhardwaj",
    "Dr. Dinesh Verma",
    "Dr. Garima Pureha",
    "Dr. Gaurav Kamra",
    "Dr. Gourav Jain",
    "Dr. Gulzar Ahmada Dar",
    "Dr. Gurjot Singh",
    "Dr. H.S. Bhandari",
    "Dr. Hardev Singh",
    "Dr. Hari Kishan",
    "Dr. Hemant Goyal",
    "Dr. Himanshu Yadav",
    "Dr. Huzafia Nazir",
    "Dr. Ifra Jan",
    "Dr. Imtiaz Ahmad",
    "Dr. Indranil Halder",
    "Dr. Indresh Dixit",
    "Dr. Jaideep Malhotra",
    "Dr. Jan Mohammad",
    "Dr. Javed Akhtar",
    "Dr. Jitendra Singh Bishnoi",
    "Dr. Jyoti Jangra",
    "Dr. Jyotsana Singh",
    "Dr. K.G. Yadav",
    "Dr. Karishma Gupta",
    "Dr. Lakhan Singh Galav",
    "Dr. Lakshika Chauhan",
    "Dr. Laxmikant Sharma",
    "Dr. Lubna Khan",
    "Dr. M.s Agrawal",
    "Dr. Maansi Sethi",
    "Dr. Mamta Bisht",
    "Dr. Manish Mahajan",
    "Dr. Manish Sharma",
    "Dr. Manish Vardhan",
    "Dr. Manish Verma",
    "Dr. Manisha Rathi",
    "Dr. Manjari Gupta",
    "Dr. Manjit Kundu",
    "Dr. Manoj Sharma",
    "Dr. Manpreet Sharma",
    "Dr. Mansi Arora",
    "Dr. Manu Mahajan",
    "Dr. Manvendra Chauhan",
    "Dr. Mayank Bansal",
    "Dr. Medha Vyas",
    "Dr. Meenakshi Gupta",
    "Dr. Mir Intikhab Maqbool",
    "Dr. Mohammad Dawood",
    "Dr. Mohd Haseeb Beg",
    "Dr. Mohd Hashim",
    "Dr. Mohit Gupta",
    "Dr. Mohit Saxena",
    "Dr. Mohmad Iqbal",
    "Dr. Monika Sanjay Gangurde",
    "Dr. Mrityunjoy Sarkar",
    "Dr. Mukul Gaba",
    "Dr. Muzaffar Ahmad Bhat",
    "Dr. N.K.Tripathi",
    "Dr. Nancy Khanna",
    "Dr. Narender Kumar",
    "Dr. Narendra Malhotra",
    "Dr. Naveen Chandra Lohani",
    "Dr. Neelaksh Kaul",
    "Dr. Neelesh Dange",
    "Dr. Neeraj Kumar",
    "Dr. Neeraj Kumar Singh",
    "Dr. Neha Bhatia",
    "Dr. Nikhilesh Singh",
    "Dr. Nikita Pahuja",
    "Dr. Nirdosh Chhabra",
    "Dr. Nisha Chhabra",
    "Dr. Nishant Verma",
    "Dr. Nishat Akhtar",
    "Dr. Nitin Kumar",
    "Dr. Nitin Manral",
    "Dr. Nityanand Tripathi",
    "Dr. Omar Bachh",
    "Dr. Omar Khursheed",
    "Dr. Ovais Peerzada",
    "Dr. Pallav Gupta",
    "Dr. Pankaj Jain",
    "Dr. Pankaj Kumar Bassan",
    "Dr. Paramjeet Singh",
    "Dr. Perveez Ahmad Malik",
    "Dr. Pervej Sofi",
    "Dr. Pinky Sankhla",
    "Dr. Prachi Mehta",
    "Dr. Pragati Rani",
    "Dr. Prakash Pursnani",
    "Dr. Prateek Ahlawat",
    "Dr. Prateek Ahuja",
    "Dr. Pratibha Gururani",
    "Dr. Pratibha Juyal",
    "Dr. Pratibha Roy",
    "Dr. Premashish Mazumdar",
    "Dr. Pritul Saxena",
    "Dr. Priya Ranjan",
    "Dr. Priyanka Garg",
    "Dr. Pyush Rai",
    "Dr. R.C Mishra",
    "Dr. Radhika Bhogwari",
    "Dr. Raghav Singhal",
    "Dr. Rahul Gupta",
    "Dr. Rahul Rishi",
    "Dr. Rajat Goyal",
    "Dr. Rajat Kapoor",
    "Dr. Rajat Tak",
    "Dr. Rajeev Kumar Gupta",
    "Dr. Rajkumar Singh",
    "Dr. Rajneesh Shekhsariya",
    "Dr. Ratiesh Kumar Raman",
    "Dr. Ratish Kumar Raman",
    "Dr. Ravneesh Gupta",
    "Dr. Ravnish Ram Krishan Gupta",
    "Dr. Rease Noor Khan",
    "Dr. Richa Tayal",
    "Dr. Rima Sharma",
    "Dr. Ritu",
    "Dr. Rohit Gera",
    "Dr. Rouf Hussain Tak",
    "Dr. S.S. Rai",
    "Dr. Sachin",
    "Dr. Sachin Chakarvarti",
    "Dr. Sadia Lanker",
    "Dr. Salim Khan",
    "Dr. Sameer Bhardwaj",
    "Dr. Sameer Gupta",
    "Dr. Sana Kausar",
    "Dr. Sana Zafar",
    "Dr. Sandeep Gaikwad",
    "Dr. Sangeeta V Yakatapure",
    "Dr. Sanjai Rastogi",
    "Dr. Sanjay Kumar",
    "Dr. Sanjay Mehta",
    "Dr. Sanjeev Agrawal",
    "Dr. Sanjeev Sharma",
    "Dr. Santosh",
    "Dr. Satpal Bhanot",
    "Dr. Satya Veer Singh",
    "Dr. Satyam Roy",
    "Dr. Seema Gogia",
    "Dr. Sekhar Singh",
    "Dr. Shafaqat",
    "Dr. Shafaqat Gaffar",
    "Dr. Shalabh Arora",
    "Dr. Shalini Trivedi",
    "Dr. Shashank Chauhan",
    "Dr. Shashikant V.V",
    "Dr. Shavika Mehta Kalra",
    "Dr. Shekhar Singh",
    "Dr. Shemi Bansal",
    "Dr. Shikha Malik",
    "Dr. Shiv Kumar Goyal",
    "Dr. Shivanshu Gupta",
    "Dr. Siddharth Dubey",
    "Dr. Siddharth Mishra",
    "Dr. Siraz Malik",
    "Dr. Sitender",
    "Dr. Sonam Pandya",
    "Dr. Sonia Singh",
    "Dr. Sourabh Mishra",
    "Dr. Sudhindra Kumar Dwivedi",
    "Dr. Sudip Chakraborty",
    "Dr. Sukumar Pandya",
    "Dr. Sumit Kumar Rana",
    "Dr. Sunil Jee Bhat",
    "Dr. Surender Singh",
    "Dr. Tarun Grover",
    "Dr. Tarun Mittal",
    "Dr. Tasreefa",
    "Dr. Trapti Saran",
    "Dr. Triveni Prasad Paliwal",
    "Dr. Umang Singla",
    "Dr. Usha Rani",
    "Dr. Vandana",
    "Dr. Vandana Kalra",
    "Dr. Vandana Thakur",
    "Dr. Veena Joshi",
    "Dr. Vibhor Agarwal",
    "Dr. Vibhore Agarwal",
    "Dr. Vijay Gupta",
    "Dr. Vijay Kumar",
    "Dr. Vijayant Kumar Sachan",
    "Dr. Vijayveer Singh",
    "Dr. Vijeta Dahiya",
    "Dr. Vikash Kumar",
    "Dr. Vikash Kumar Arya",
    "Dr. Vinay Mittal",
    "Dr. Vinay Tiwari",
    "Dr. Vineet Agarwal",
    "Dr. Vineet Kumar",
    "Dr. Vinesh Jain",
    "Dr. Vipin Kumar",
    "Dr. Vishal Gupta",
    "Dr. Waseem Ahmad",
    "Dr. Yaser Ahmad",
    "Dr. Yogesh Nagendra",
    "Dr. Yuvraj Gulati"
]

# Function to generate URLs
def generate_urls(names):
    urls = []
    for name in names:
        # Remove "Dr." and other prefixes, replace spaces with hyphens, convert to lowercase
        formatted_name = name.replace("Dr.", "dr").strip()
        formatted_name = formatted_name.lower().replace(" ", "-")
        # Create the URL
        url = f"https://ujalacygnus.com/profile/{formatted_name}"
        urls.append(url)
    return urls

# Generate the URLs
doctor_urls = generate_urls(doctor_names)

# Convert to JSON
json_output = json.dumps(doctor_urls, indent=4)

# Write to a JSON file
with open('doctor_urls.json', 'w') as file:
    file.write(json_output)

# Print the output
print(json_output)
